#!/usr/bin/env python3
"""
Build derived IPO timing analysis for the static page.

Reads:
- ipo-data.js
- chart-data.js

Writes:
- ipo-analysis.js

The browser still draws the analysis panel, but the statistics are computed
here so the page receives a compact data product instead of doing the analysis
at runtime.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import pathlib
import re
import sys
from typing import Any


MARKET_OPEN_MINUTES = 9 * 60 + 30
ANALYSIS_YEARS = 15
REFRESH_DATE = dt.date.today().isoformat()

ANALYSIS_BUCKETS = [
    {"label": "0-30m", "minMinutes": 0, "maxMinutes": 30},
    {"label": "30-60m", "minMinutes": 30, "maxMinutes": 60},
    {"label": "1-2h", "minMinutes": 60, "maxMinutes": 120},
    {"label": "2-3h", "minMinutes": 120, "maxMinutes": 180},
    {"label": "3-4h", "minMinutes": 180, "maxMinutes": 240},
    {"label": "4h+", "minMinutes": 240, "maxMinutes": None},
]

CLOCK_TIME_BUCKETS = [
    {"label": "09:30-11:00", "startMinute": 9 * 60 + 30, "endMinute": 11 * 60},
    {"label": "11:00-12:00", "startMinute": 11 * 60, "endMinute": 12 * 60},
    {"label": "12:00-13:00", "startMinute": 12 * 60, "endMinute": 13 * 60},
    {"label": "13:00-14:00", "startMinute": 13 * 60, "endMinute": 14 * 60},
    {"label": "14:00-15:00", "startMinute": 14 * 60, "endMinute": 15 * 60},
    {"label": "15:00-16:00", "startMinute": 15 * 60, "endMinute": 16 * 60},
]

EXPERT_NOTES = [
    {
        "source": "SEC Investor.gov",
        "url": "https://www.sec.gov/files/ipo-investorbulletin.pdf",
        "text": "Read the prospectus and remember that SEC review is not an endorsement of the IPO or a guarantee that disclosures are complete or accurate.",
    },
    {
        "source": "Charles Schwab",
        "url": "https://www.schwab.com/learn/story/ipo-basics-what-to-know-before-investing",
        "text": "Use caution around IPO hype; Schwab says it can be beneficial to wait until the stock trades and, if buying, consider smaller purchases over time.",
    },
    {
        "source": "Fidelity",
        "url": "https://www.fidelity.com/stock-trading/faqs-ipos",
        "text": "First trades usually do not happen at the 09:30 market open; Fidelity says IPOs typically begin between 10:00 and 14:00 ET.",
    },
]


class Seeded:
    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def __call__(self) -> float:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state / 4294967296


def read_window_assignment(path: pathlib.Path, variable: str) -> Any:
    text = path.read_text(encoding="utf-8")
    match = re.search(rf"window\.{re.escape(variable)}\s*=\s*(.*?);\s*$", text, re.S)
    if not match:
        raise ValueError(f"Could not find window.{variable} assignment in {path}")
    return json.loads(match.group(1))


def write_js(path: pathlib.Path, variable: str, data: Any) -> None:
    today = dt.date.today().isoformat()
    header = [
        f"// Generated by build_ipo_analysis.py on {today}.",
        "// Source: ipo-data.js",
        "// Source: chart-data.js",
        *[f"// Research: {note['url']}" for note in EXPERT_NOTES],
        f"window.{variable} = ",
    ]
    path.write_text("\n".join(header) + json.dumps(data, indent=2) + ";\n", encoding="utf-8")


def time_to_minutes(time_s: str | None) -> int | None:
    if not time_s:
        return None
    try:
        hours, minutes = [int(part) for part in time_s.split(":", 1)]
    except ValueError:
        return None
    return hours * 60 + minutes


def minutes_to_time(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def js_hash_ticker(ticker: str) -> int:
    acc = 17
    for char in ticker:
        acc = ((acc * 31) + ord(char)) & 0xFFFFFFFF
    return acc


def clamp(value: float, min_value: float, max_value: float) -> float:
    return max(min_value, min(max_value, value))


def estimated_volume_at(index: int, total_bars: int, daily_volume: float | None, rng: Seeded) -> int:
    open_close_bias = 0.75 + abs((index / max(total_bars - 1, 1)) - 0.5) * 1.6
    pulse = 1.7 if index < 8 or index > total_bars - 9 else 1
    noise = 0.75 + rng() * 0.7
    base = daily_volume / total_bars if daily_volume else 100000
    return max(1, round(base * open_close_bias * pulse * noise))


def estimated_bars_from_daily(ipo: dict[str, Any], daily: dict[str, Any]) -> list[dict[str, Any]]:
    rng = Seeded(js_hash_ticker(f"{ipo['ticker']}-daily"))
    open_ = float(daily["open"])
    close = float(daily["close"])
    high_target = max(float(daily["high"]), open_, close)
    low_target = min(float(daily["low"]), open_, close)
    daily_volume = float(daily["volume"]) if daily.get("volume") else None
    range_ = max(high_target - low_target, max(abs(open_), abs(close), 1) * 0.01)
    high_slot = 10 + math.floor(rng() * 22)
    low_slot = 34 + math.floor(rng() * 28)
    bars: list[dict[str, Any]] = []
    last = open_
    for index in range(78):
        progress = index / 77
        base = open_ + (close - open_) * progress
        wave = math.sin(progress * math.pi * 2.4 + rng() * 2) * range_ * 0.12
        noise = (rng() - 0.5) * range_ * 0.08
        high_pulse = math.exp(-((index - high_slot) / 7) ** 2) * range_ * 0.28
        low_pulse = math.exp(-((index - low_slot) / 7) ** 2) * range_ * 0.28
        next_ = close if index == 77 else clamp(base + wave + noise + high_pulse - low_pulse, low_target, high_target)
        wick = range_ * (0.04 + rng() * 0.08)
        high = high_target if index == high_slot else min(high_target, max(last, next_) + wick)
        low = low_target if index == low_slot else max(low_target, min(last, next_) - wick)
        minute = MARKET_OPEN_MINUTES + index * 5
        bars.append(
            {
                "index": index,
                "time": minutes_to_time(minute),
                "minute": minute,
                "open": last,
                "high": high,
                "low": low,
                "close": next_,
                "volume": estimated_volume_at(index, 78, daily_volume, rng),
                "source": "Yahoo 1d estimate",
            }
        )
        last = next_
    return bars


def fallback_bars(ipo: dict[str, Any]) -> list[dict[str, Any]]:
    rng = Seeded(js_hash_ticker(str(ipo["ticker"])))
    close = float(ipo.get("current") or ipo.get("ipoPrice") or 10)
    ipo_pop = 1 + max(-0.35, min(1.25, float(ipo.get("dayChange") or 0) / 100))
    open_ = max(0.5, close / max(0.35, ipo_pop))
    range_base = max(open_, close) * (0.08 + rng() * 0.08)
    high_target = max(open_, close) + range_base * (0.45 + rng())
    low_target = max(0.5, min(open_, close) - range_base * (0.45 + rng()))
    bars: list[dict[str, Any]] = []
    last = open_
    for index in range(78):
        progress = index / 77
        drift = open_ + (close - open_) * progress
        wave = math.sin(progress * math.pi * 2.6 + rng() * 1.8) * range_base * 0.24
        noise = (rng() - 0.5) * range_base * 0.18
        next_ = close if index == 77 else max(low_target, min(high_target, drift + wave + noise))
        wick = range_base * (0.05 + rng() * 0.12)
        high = min(high_target, max(last, next_) + wick)
        low = max(low_target, min(last, next_) - wick)
        minute = MARKET_OPEN_MINUTES + index * 5
        bars.append(
            {
                "index": index,
                "time": minutes_to_time(minute),
                "minute": minute,
                "open": last,
                "high": high,
                "low": low,
                "close": next_,
                "volume": estimated_volume_at(index, 78, None, rng),
                "source": "fallback",
            }
        )
        last = next_
    return bars


def chart_data(ipo: dict[str, Any], first_day_bars: dict[str, list[list[Any]]]) -> list[dict[str, Any]]:
    rows = first_day_bars.get(ipo["ticker"])
    if rows:
        out = []
        for index, row in enumerate(rows):
            out.append(
                {
                    "index": index,
                    "time": row[0],
                    "minute": time_to_minutes(row[0]),
                    "open": row[1],
                    "high": row[2],
                    "low": row[3],
                    "close": row[4],
                    "volume": row[5],
                    "source": "Yahoo 5m",
                }
            )
        return out
    first_day = ipo.get("firstDay")
    if first_day and all(is_finite_number(first_day.get(key)) for key in ["open", "high", "low", "close"]):
        return estimated_bars_from_daily(ipo, first_day)
    return fallback_bars(ipo)


def is_finite_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and math.isfinite(value)


def chart_low_point(data: list[dict[str, Any]]) -> dict[str, Any] | None:
    valid = [bar for bar in data if is_finite_number(bar.get("low")) and is_finite_number(bar.get("minute"))]
    if not valid:
        return None
    return min(valid, key=lambda bar: bar["low"])


def median(values: list[float]) -> float | None:
    sorted_values = sorted(value for value in values if math.isfinite(value))
    if not sorted_values:
        return None
    mid = len(sorted_values) // 2
    if len(sorted_values) % 2:
        return sorted_values[mid]
    return (sorted_values[mid - 1] + sorted_values[mid]) / 2


def years_ago(date_s: str, years: int) -> str:
    date = dt.date.fromisoformat(date_s)
    try:
        return date.replace(year=date.year - years).isoformat()
    except ValueError:
        return date.replace(year=date.year - years, day=28).isoformat()


def bucket_for_delta(delta: float) -> dict[str, Any]:
    for bucket in ANALYSIS_BUCKETS:
        max_minutes = bucket["maxMinutes"]
        if delta >= bucket["minMinutes"] and (max_minutes is None or delta < max_minutes):
            return bucket
    return ANALYSIS_BUCKETS[-1]


def bucket_for_clock_time(minute: float) -> dict[str, Any]:
    for bucket in CLOCK_TIME_BUCKETS:
        if minute >= bucket["startMinute"] and minute < bucket["endMinute"]:
            return bucket
    return CLOCK_TIME_BUCKETS[-1]


def round_or_none(value: float | None, places: int = 2) -> float | None:
    return None if value is None else round(value, places)


def source_key(source: str) -> str:
    if source == "Yahoo 5m":
        return "exact5m"
    if source == "Yahoo 1d estimate":
        return "dailyEstimate"
    return "syntheticFallback"


def low_timing_record(ipo: dict[str, Any], first_day_bars: dict[str, list[list[Any]]]) -> dict[str, Any] | None:
    data = chart_data(ipo, first_day_bars)
    low = chart_low_point(data)
    first = data[0] if data else None
    if not low or not first or not is_finite_number(first.get("minute")):
        return None
    delta = low["minute"] - first["minute"]
    bucket = bucket_for_delta(delta)
    clock_bucket = bucket_for_clock_time(low["minute"])
    return {
        "ticker": ipo["ticker"],
        "name": ipo["name"],
        "date": ipo["date"],
        "marketCap": round_or_none(ipo.get("marketCap")),
        "source": low.get("source") or first.get("source") or "fallback",
        "firstTime": first.get("time") or minutes_to_time(first["minute"]),
        "lowTime": low.get("time") or minutes_to_time(low["minute"]),
        "firstMinute": int(first["minute"]),
        "lowMinute": int(low["minute"]),
        "deltaMinutes": int(round(delta)),
        "lowPrice": round_or_none(float(low["low"])),
        "bucket": bucket["label"],
        "clockBucket": clock_bucket["label"],
    }


def build_analysis(ipos: list[dict[str, Any]], first_day_bars: dict[str, list[list[Any]]], *, as_of: str = REFRESH_DATE) -> dict[str, Any]:
    cutoff = years_ago(as_of, ANALYSIS_YEARS)
    all_records = [
        low_timing_record(ipo, first_day_bars)
        for ipo in ipos
        if ipo.get("date") and ipo["date"] >= cutoff
    ]
    all_records = [record for record in all_records if record]
    records = [record for record in all_records if record["source"] != "fallback"]
    deltas = [float(record["deltaMinutes"]) for record in records]
    source_counts = {
        "exact5m": sum(1 for record in records if source_key(record["source"]) == "exact5m"),
        "dailyEstimate": sum(1 for record in records if source_key(record["source"]) == "dailyEstimate"),
        "syntheticOmitted": sum(1 for record in all_records if source_key(record["source"]) == "syntheticFallback"),
    }
    buckets = []
    for bucket in ANALYSIS_BUCKETS:
        count = sum(1 for record in records if record["bucket"] == bucket["label"])
        buckets.append(
            {
                **bucket,
                "count": count,
                "pct": round_or_none(count / len(records) * 100 if records else None, 1),
            }
        )
    clock_buckets = []
    for bucket in CLOCK_TIME_BUCKETS:
        count = sum(1 for record in records if record["clockBucket"] == bucket["label"])
        clock_buckets.append(
            {
                **bucket,
                "count": count,
                "pct": round_or_none(count / len(records) * 100 if records else None, 1),
            }
        )
    top_bucket = max(buckets, key=lambda bucket: (bucket["count"], -bucket["minMinutes"])) if buckets else None
    top_clock_bucket = max(clock_buckets, key=lambda bucket: (bucket["count"], -bucket["startMinute"])) if clock_buckets else None
    fastest = min(records, key=lambda record: record["deltaMinutes"]) if records else None
    latest = max(records, key=lambda record: record["deltaMinutes"]) if records else None
    first_hour = sum(1 for record in records if record["deltaMinutes"] < 60)
    after_two_hours = sum(1 for record in records if record["deltaMinutes"] >= 120)
    noon_or_later = sum(1 for record in records if record["lowMinute"] >= 12 * 60)
    median_low_minute = median([float(record["lowMinute"]) for record in records])
    return {
        "generatedAt": dt.date.today().isoformat(),
        "asOf": as_of,
        "windowYears": ANALYSIS_YEARS,
        "cutoffDate": cutoff,
        "sampleSize": len(records),
        "sourceCounts": source_counts,
        "medianDeltaMinutes": round_or_none(median(deltas), 1),
        "medianLowMinute": round_or_none(median_low_minute, 1),
        "medianLowTime": minutes_to_time(round(median_low_minute)) if median_low_minute is not None else None,
        "firstHourPct": round_or_none(first_hour / len(records) * 100 if records else None, 1),
        "afterTwoHoursPct": round_or_none(after_two_hours / len(records) * 100 if records else None, 1),
        "noonOrLaterPct": round_or_none(noon_or_later / len(records) * 100 if records else None, 1),
        "topBucket": top_bucket,
        "topClockBucket": top_clock_bucket,
        "fastestLow": fastest,
        "latestLow": latest,
        "buckets": buckets,
        "clockBuckets": clock_buckets,
        "records": sorted(records, key=lambda record: (record["deltaMinutes"], record["ticker"])),
        "expertNotes": EXPERT_NOTES,
        "methodology": "Uses exact Yahoo 5-minute bars where available; otherwise mirrors the site's Yahoo daily-OHLC intraday estimate. Clock times are US/Eastern market time. Synthetic fallback charts are omitted from the summary statistics.",
    }


def build_analysis_file(input_dir: pathlib.Path, output_dir: pathlib.Path | None = None, *, as_of: str = REFRESH_DATE) -> pathlib.Path:
    input_dir = input_dir.resolve()
    output_dir = (output_dir or input_dir).resolve()
    ipos = read_window_assignment(input_dir / "ipo-data.js", "ipos")
    first_day_bars = read_window_assignment(input_dir / "chart-data.js", "firstDayBars")
    analysis = build_analysis(ipos, first_day_bars, as_of=as_of)
    output_path = output_dir / "ipo-analysis.js"
    write_js(output_path, "ipoAnalysis", analysis)
    return output_path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build derived IPO timing analysis data.")
    parser.add_argument("--input-dir", default=".", help="directory containing ipo-data.js and chart-data.js")
    parser.add_argument("--output-dir", default=None, help="directory to write ipo-analysis.js; defaults to input-dir")
    parser.add_argument("--as-of", default=REFRESH_DATE, help="analysis date used for the rolling 15-year cutoff")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    path = build_analysis_file(
        pathlib.Path(args.input_dir),
        pathlib.Path(args.output_dir) if args.output_dir else None,
        as_of=args.as_of,
    )
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
