#!/usr/bin/env python3
"""
Build derived IPO timing analysis for the static page.

Reads:
- ipo-data.js
- chart-data.js

Writes:
- ipo-analysis.js

The browser still draws the analysis panel, but the statistics are computed
here so the page receives a compact data product instead of doing the analysis
at runtime.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import pathlib
import re
import sys
from typing import Any
from zoneinfo import ZoneInfo


MARKET_OPEN_MINUTES = 9 * 60 + 30
ANALYSIS_YEARS = 15
REFRESH_DATE = dt.date.today().isoformat()
NYC = ZoneInfo("America/New_York")
BERLIN = ZoneInfo("Europe/Berlin")

ANALYSIS_BUCKETS = [
    {"label": "0-30m", "minMinutes": 0, "maxMinutes": 30},
    {"label": "30-60m", "minMinutes": 30, "maxMinutes": 60},
    {"label": "1-2h", "minMinutes": 60, "maxMinutes": 120},
    {"label": "2-3h", "minMinutes": 120, "maxMinutes": 180},
    {"label": "3-4h", "minMinutes": 180, "maxMinutes": 240},
    {"label": "4h+", "minMinutes": 240, "maxMinutes": None},
]

CLOCK_TIME_BUCKETS = [
    {"label": "09:30-11:00", "startMinute": 9 * 60 + 30, "endMinute": 11 * 60},
    {"label": "11:00-12:00", "startMinute": 11 * 60, "endMinute": 12 * 60},
    {"label": "12:00-13:00", "startMinute": 12 * 60, "endMinute": 13 * 60},
    {"label": "13:00-14:00", "startMinute": 13 * 60, "endMinute": 14 * 60},
    {"label": "14:00-15:00", "startMinute": 14 * 60, "endMinute": 15 * 60},
    {"label": "15:00-16:00", "startMinute": 15 * 60, "endMinute": 16 * 60},
]

DECISION_CHECKPOINTS = [
    (15, "Wait 15m"),
    (30, "Wait 30m"),
    (45, "Wait 45m"),
    (60, "Wait 1h"),
    (90, "Wait 90m"),
    (120, "Wait 2h"),
]

EXPERT_NOTES = [
    {
        "source": "SEC Investor.gov",
        "url": "https://www.sec.gov/files/ipo-investorbulletin.pdf",
        "text": "Read the prospectus and remember that SEC review is not an endorsement of the IPO or a guarantee that disclosures are complete or accurate.",
    },
    {
        "source": "Charles Schwab",
        "url": "https://www.schwab.com/learn/story/ipo-basics-what-to-know-before-investing",
        "text": "Use caution around IPO hype; Schwab says it can be beneficial to wait until the stock trades and, if buying, consider smaller purchases over time.",
    },
    {
        "source": "Fidelity",
        "url": "https://www.fidelity.com/stock-trading/faqs-ipos",
        "text": "First trades usually do not happen at the 09:30 market open; Fidelity says IPOs typically begin between 10:00 and 14:00 ET.",
    },
]


def read_window_assignment(path: pathlib.Path, variable: str) -> Any:
    text = path.read_text(encoding="utf-8")
    match = re.search(rf"window\.{re.escape(variable)}\s*=\s*(.*?);\s*(?:\n|$)", text, re.S)
    if not match:
        raise ValueError(f"Could not find window.{variable} assignment in {path}")
    return json.loads(match.group(1))


def read_optional_window_assignment(path: pathlib.Path, variable: str, default: Any) -> Any:
    try:
        return read_window_assignment(path, variable)
    except ValueError:
        return default


def write_js(path: pathlib.Path, variable: str, data: Any) -> None:
    today = dt.date.today().isoformat()
    header = [
        f"// Generated by build_ipo_analysis.py on {today}.",
        "// Source: ipo-data.js",
        "// Source: chart-data.js",
        *[f"// Research: {note['url']}" for note in EXPERT_NOTES],
        f"window.{variable} = ",
    ]
    path.write_text("\n".join(header) + json.dumps(data, indent=2) + ";\n", encoding="utf-8")


def time_to_minutes(time_s: str | None) -> int | None:
    if not time_s:
        return None
    try:
        hours, minutes = [int(part) for part in time_s.split(":", 1)]
    except ValueError:
        return None
    return hours * 60 + minutes


def minutes_to_time(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def market_datetime(date_s: str, minute: int, zone: ZoneInfo = NYC) -> dt.datetime:
    date = dt.date.fromisoformat(date_s)
    return dt.datetime(date.year, date.month, date.day, minute // 60, minute % 60, tzinfo=zone)


def german_zone_label(value: dt.datetime) -> str:
    return {"CET": "MEZ", "CEST": "MESZ"}.get(value.tzname() or "", value.tzname() or "MEZ")


def berlin_datetime(date_s: str, minute: int) -> dt.datetime:
    return market_datetime(date_s, minute, NYC).astimezone(BERLIN)


def berlin_time_label(date_s: str, minute: int) -> str:
    return berlin_datetime(date_s, minute).strftime("%H:%M")


def berlin_range_parts(date_s: str, start_minute: int, end_minute: int) -> tuple[str, str]:
    start = berlin_datetime(date_s, start_minute)
    end = berlin_datetime(date_s, end_minute)
    time_range = f"{start:%H:%M}-{end:%H:%M}"
    zone_labels = []
    for value in [start, end]:
        label = german_zone_label(value)
        if label not in zone_labels:
            zone_labels.append(label)
    return time_range, "/".join(zone_labels)


def time_range_minutes(time_range: str) -> tuple[int, int] | None:
    try:
        start_s, end_s = time_range.split("-", 1)
    except ValueError:
        return None
    start = time_to_minutes(start_s)
    end = time_to_minutes(end_s)
    if start is None or end is None:
        return None
    return start, end


def german_chart_label(time_ranges: list[str]) -> str:
    parsed = [parts for value in time_ranges if (parts := time_range_minutes(value))]
    if not parsed:
        return ""
    start = min(parts[0] for parts in parsed)
    end = max(parts[1] for parts in parsed)
    return f"{minutes_to_time(start)}-{minutes_to_time(end)} (DE)"


def chart_data(ipo: dict[str, Any], first_day_bars: dict[str, list[list[Any]]], first_day_bar_sources: dict[str, str] | None = None) -> list[dict[str, Any]]:
    rows = first_day_bars.get(ipo["ticker"])
    if rows:
        out = []
        source = (first_day_bar_sources or {}).get(ipo["ticker"], "5m bars")
        for index, row in enumerate(rows):
            out.append(
                {
                    "index": index,
                    "time": row[0],
                    "minute": time_to_minutes(row[0]),
                    "open": row[1],
                    "high": row[2],
                    "low": row[3],
                    "close": row[4],
                    "volume": row[5],
                    "source": source,
                }
            )
        return out
    return []


def is_finite_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and math.isfinite(value)


def chart_low_point(data: list[dict[str, Any]]) -> dict[str, Any] | None:
    valid = [bar for bar in data if is_finite_number(bar.get("low")) and is_finite_number(bar.get("minute"))]
    if not valid:
        return None
    return min(valid, key=lambda bar: bar["low"])


def median(values: list[float]) -> float | None:
    sorted_values = sorted(value for value in values if math.isfinite(value))
    if not sorted_values:
        return None
    mid = len(sorted_values) // 2
    if len(sorted_values) % 2:
        return sorted_values[mid]
    return (sorted_values[mid - 1] + sorted_values[mid]) / 2


def years_ago(date_s: str, years: int) -> str:
    date = dt.date.fromisoformat(date_s)
    try:
        return date.replace(year=date.year - years).isoformat()
    except ValueError:
        return date.replace(year=date.year - years, day=28).isoformat()


def bucket_for_delta(delta: float) -> dict[str, Any]:
    for bucket in ANALYSIS_BUCKETS:
        max_minutes = bucket["maxMinutes"]
        if delta >= bucket["minMinutes"] and (max_minutes is None or delta < max_minutes):
            return bucket
    return ANALYSIS_BUCKETS[-1]


def bucket_for_clock_time(minute: float) -> dict[str, Any]:
    for bucket in CLOCK_TIME_BUCKETS:
        if minute >= bucket["startMinute"] and minute < bucket["endMinute"]:
            return bucket
    return CLOCK_TIME_BUCKETS[-1]


def round_or_none(value: float | None, places: int = 2) -> float | None:
    return None if value is None else round(value, places)


def decision_checkpoints(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    total = len(records)
    out = []
    for minutes, label in DECISION_CHECKPOINTS:
        still_ahead = sum(1 for record in records if record["deltaMinutes"] >= minutes)
        missed = total - still_ahead
        out.append(
            {
                "label": label,
                "minutes": minutes,
                "stillAheadCount": still_ahead,
                "stillAheadPct": round_or_none(still_ahead / total * 100 if total else None, 1),
                "missedCount": missed,
                "missedPct": round_or_none(missed / total * 100 if total else None, 1),
            }
        )
    return out


def pct_count(count: int, total: int) -> dict[str, Any]:
    return {
        "count": count,
        "pct": round_or_none(count / total * 100 if total else None, 1),
    }


def decision_insights(records: list[dict[str, Any]], checkpoints: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(records)
    first_print_low = sum(1 for record in records if record["deltaMinutes"] == 0)
    first_30 = sum(1 for record in records if record["deltaMinutes"] < 30)
    after_noon = sum(1 for record in records if record["lowMinute"] >= 12 * 60)
    after_13 = sum(1 for record in records if record["lowMinute"] >= 13 * 60)
    after_14 = sum(1 for record in records if record["lowMinute"] >= 14 * 60)
    final_hour = sum(1 for record in records if record["lowMinute"] >= 15 * 60)
    even_odds = [checkpoint for checkpoint in checkpoints if (checkpoint.get("stillAheadPct") or 0) >= 50]
    last_even_odds = even_odds[-1] if even_odds else None
    return {
        "openingPrintLow": pct_count(first_print_low, total),
        "openingRushLow": pct_count(first_30, total),
        "lowAfterNoon": pct_count(after_noon, total),
        "lowAfter13": pct_count(after_13, total),
        "lowAfter14": pct_count(after_14, total),
        "finalHourLow": pct_count(final_hour, total),
        "lastEvenOddsWait": last_even_odds,
    }


def low_timing_record(ipo: dict[str, Any], first_day_bars: dict[str, list[list[Any]]], first_day_bar_sources: dict[str, str] | None = None) -> dict[str, Any] | None:
    data = chart_data(ipo, first_day_bars, first_day_bar_sources)
    low = chart_low_point(data)
    first = data[0] if data else None
    if not low or not first or not is_finite_number(first.get("minute")):
        return None
    delta = low["minute"] - first["minute"]
    bucket = bucket_for_delta(delta)
    clock_bucket = bucket_for_clock_time(low["minute"])
    low_berlin = berlin_datetime(ipo["date"], int(low["minute"]))
    first_minute = int(first["minute"])
    low_minute = int(low["minute"])
    low_berlin_minute = low_berlin.hour * 60 + low_berlin.minute
    return {
        "ticker": ipo["ticker"],
        "name": ipo["name"],
        "date": ipo["date"],
        "marketCap": round_or_none(ipo.get("marketCap")),
        "source": first.get("source") or "5m bars",
        "firstTime": minutes_to_time(first_minute),
        "lowTime": minutes_to_time(low_minute),
        "firstBerlinTime": berlin_time_label(ipo["date"], first_minute),
        "lowBerlinTime": f"{low_berlin:%H:%M}",
        "lowBerlinZone": german_zone_label(low_berlin),
        "lowBerlinMinute": low_berlin_minute,
        "firstMinute": first_minute,
        "lowMinute": low_minute,
        "deltaMinutes": int(round(delta)),
        "lowPrice": round_or_none(float(low["low"])),
        "bucket": bucket["label"],
        "clockBucket": clock_bucket["label"],
    }


def build_analysis(ipos: list[dict[str, Any]], first_day_bars: dict[str, list[list[Any]]], first_day_bar_sources: dict[str, str] | None = None, *, as_of: str = REFRESH_DATE) -> dict[str, Any]:
    cutoff = years_ago(as_of, ANALYSIS_YEARS)
    analysis_ipos = [
        ipo
        for ipo in ipos
        if ipo.get("date") and ipo["date"] >= cutoff
    ]
    records = [
        low_timing_record(ipo, first_day_bars, first_day_bar_sources)
        for ipo in analysis_ipos
    ]
    records = [record for record in records if record]
    deltas = [float(record["deltaMinutes"]) for record in records]
    source_counts = {
        "exact5m": len(records),
        "missingExact5m": max(0, len(analysis_ipos) - len(records)),
    }
    buckets = []
    for bucket in ANALYSIS_BUCKETS:
        count = sum(1 for record in records if record["bucket"] == bucket["label"])
        buckets.append(
            {
                **bucket,
                "count": count,
                "pct": round_or_none(count / len(records) * 100 if records else None, 1),
            }
        )
    clock_buckets = []
    for bucket in CLOCK_TIME_BUCKETS:
        bucket_records = [record for record in records if record["clockBucket"] == bucket["label"]]
        count = len(bucket_records)
        berlin_ranges: list[str] = []
        berlin_zones: list[str] = []
        for record in bucket_records:
            time_range, zone_label = berlin_range_parts(record["date"], bucket["startMinute"], bucket["endMinute"])
            if time_range not in berlin_ranges:
                berlin_ranges.append(time_range)
            for zone_part in zone_label.split("/"):
                if zone_part not in berlin_zones:
                    berlin_zones.append(zone_part)
        if not berlin_ranges:
            time_range, zone_label = berlin_range_parts(as_of, bucket["startMinute"], bucket["endMinute"])
            berlin_ranges.append(time_range)
            berlin_zones.extend(zone_part for zone_part in zone_label.split("/") if zone_part not in berlin_zones)
        berlin_ranges.sort()
        berlin_zones.sort(key=lambda label: {"MEZ": 0, "MESZ": 1}.get(label, 2))
        berlin_label = " / ".join(berlin_ranges)
        berlin_zone_label = "/".join(berlin_zones)
        clock_buckets.append(
            {
                **bucket,
                "count": count,
                "pct": round_or_none(count / len(records) * 100 if records else None, 1),
                "nycLabel": bucket["label"],
                "berlinLabel": berlin_label,
                "berlinZoneLabel": berlin_zone_label,
                "germanChartLabel": german_chart_label(berlin_ranges),
                "germanFullLabel": f"{berlin_zone_label} {berlin_label}".strip(),
            }
        )
    top_bucket = max(buckets, key=lambda bucket: (bucket["count"], -bucket["minMinutes"])) if buckets else None
    top_clock_bucket = max(clock_buckets, key=lambda bucket: (bucket["count"], -bucket["startMinute"])) if clock_buckets else None
    fastest = min(records, key=lambda record: record["deltaMinutes"]) if records else None
    latest = max(records, key=lambda record: record["deltaMinutes"]) if records else None
    first_hour = sum(1 for record in records if record["deltaMinutes"] < 60)
    first_30 = sum(1 for record in records if record["deltaMinutes"] < 30)
    after_two_hours = sum(1 for record in records if record["deltaMinutes"] >= 120)
    noon_or_later = sum(1 for record in records if record["lowMinute"] >= 12 * 60)
    median_low_minute = median([float(record["lowMinute"]) for record in records])
    median_low_berlin_minute = median([float(record["lowBerlinMinute"]) for record in records])
    median_low_german_time = (
        minutes_to_time(round(median_low_berlin_minute)) if median_low_berlin_minute is not None else None
    )
    checkpoints = decision_checkpoints(records)
    return {
        "generatedAt": dt.date.today().isoformat(),
        "asOf": as_of,
        "windowYears": ANALYSIS_YEARS,
        "cutoffDate": cutoff,
        "sampleSize": len(records),
        "sourceCounts": source_counts,
        "medianDeltaMinutes": round_or_none(median(deltas), 1),
        "medianLowMinute": round_or_none(median_low_minute, 1),
        "medianLowTime": minutes_to_time(round(median_low_minute)) if median_low_minute is not None else None,
        "medianLowGermanMinute": round_or_none(median_low_berlin_minute, 1),
        "medianLowGermanTime": median_low_german_time,
        "medianLowGermanLabel": f"{median_low_german_time} (DE)" if median_low_german_time else None,
        "firstHourPct": round_or_none(first_hour / len(records) * 100 if records else None, 1),
        "first30MinutesPct": round_or_none(first_30 / len(records) * 100 if records else None, 1),
        "afterTwoHoursPct": round_or_none(after_two_hours / len(records) * 100 if records else None, 1),
        "noonOrLaterPct": round_or_none(noon_or_later / len(records) * 100 if records else None, 1),
        "decisionCheckpoints": checkpoints,
        "decisionInsights": decision_insights(records, checkpoints),
        "topBucket": top_bucket,
        "topClockBucket": top_clock_bucket,
        "fastestLow": fastest,
        "latestLow": latest,
        "buckets": buckets,
        "clockBuckets": clock_buckets,
        "records": sorted(records, key=lambda record: (record["deltaMinutes"], record["ticker"])),
        "expertNotes": EXPERT_NOTES,
        "methodology": "Uses only exact first-trading-day 5-minute OHLCV bars stored in chart-data.js. No daily-OHLC estimates or synthetic fallback charts are included in the chart display or timing analysis. Clock times are US/Eastern market time.",
    }


def build_analysis_file(input_dir: pathlib.Path, output_dir: pathlib.Path | None = None, *, as_of: str = REFRESH_DATE) -> pathlib.Path:
    input_dir = input_dir.resolve()
    output_dir = (output_dir or input_dir).resolve()
    ipos = read_window_assignment(input_dir / "ipo-data.js", "ipos")
    chart_data_path = input_dir / "chart-data.js"
    first_day_bars = read_window_assignment(chart_data_path, "firstDayBars")
    first_day_bar_sources = read_optional_window_assignment(chart_data_path, "firstDayBarSources", {})
    analysis = build_analysis(ipos, first_day_bars, first_day_bar_sources, as_of=as_of)
    output_path = output_dir / "ipo-analysis.js"
    write_js(output_path, "ipoAnalysis", analysis)
    return output_path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build derived IPO timing analysis data.")
    parser.add_argument("--input-dir", default=".", help="directory containing ipo-data.js and chart-data.js")
    parser.add_argument("--output-dir", default=None, help="directory to write ipo-analysis.js; defaults to input-dir")
    parser.add_argument("--as-of", default=REFRESH_DATE, help="analysis date used for the rolling 15-year cutoff")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    path = build_analysis_file(
        pathlib.Path(args.input_dir),
        pathlib.Path(args.output_dir) if args.output_dir else None,
        as_of=args.as_of,
    )
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
