// Generated by refresh_ipo_data.py on 2026-05-25.
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GOOGL?period1=1092873600&period2=1093478400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GOOGL?period1=1092873600&period2=1092960000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GOOG?period1=1092873600&period2=1093478400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GOOG?period1=1092873600&period2=1092960000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/TSLA?period1=1277769600&period2=1278374400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/TSLA?period1=1277769600&period2=1277856000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/AMD?period1=86400000&period2=87004800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/AMD?period1=86400000&period2=86486400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ASML?period1=795225600&period2=795830400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ASML?period1=795225600&period2=795312000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/JNJ?period1=-797472000&period2=-796867200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/JNJ?period1=-797472000&period2=-797385600&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/COST?period1=748656000&period2=749260800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/COST?period1=748656000&period2=748742400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ARM?period1=1694649600&period2=1695254400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ARM?period1=1694649600&period2=1694736000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/BABA?period1=1411084800&period2=1411689600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/BABA?period1=1411084800&period2=1411171200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/AZN?period1=737164800&period2=737769600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/AZN?period1=737164800&period2=737251200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/PANW?period1=1342742400&period2=1343347200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/PANW?period1=1342742400&period2=1342828800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ANET?period1=1402012800&period2=1402617600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ANET?period1=1402012800&period2=1402099200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ADI?period1=71107200&period2=71712000&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ADI?period1=71107200&period2=71193600&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/DELL?period1=582940800&period2=583545600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/DELL?period1=582940800&period2=583027200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SAN?period1=554515200&period2=555120000&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SAN?period1=554515200&period2=554601600&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/MRVL?period1=962064000&period2=962668800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/MRVL?period1=962064000&period2=962150400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRWD?period1=1560297600&period2=1560902400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRWD?period1=1560297600&period2=1560384000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRM?period1=1087948800&period2=1088553600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRM?period1=1087948800&period2=1088035200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/UBER?period1=1557446400&period2=1558051200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/UBER?period1=1557446400&period2=1557532800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/PDD?period1=1532563200&period2=1533168000&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/PDD?period1=1532563200&period2=1532649600&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SHOP?period1=1432166400&period2=1432771200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SHOP?period1=1432166400&period2=1432252800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SONY?period1=-349833600&period2=-349228800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SONY?period1=-349833600&period2=-349747200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SPOT?period1=1522713600&period2=1523318400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/SPOT?period1=1522713600&period2=1522800000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/NOW?period1=1340928000&period2=1341532800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/NOW?period1=1340928000&period2=1341014400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CDNS?period1=550281600&period2=550886400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CDNS?period1=550281600&period2=550368000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/HOOD?period1=1627516800&period2=1628121600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/HOOD?period1=1627516800&period2=1627603200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/NU?period1=1639008000&period2=1639612800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/NU?period1=1639008000&period2=1639094400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRWV?period1=1743120000&period2=1743724800&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRWV?period1=1743120000&period2=1743206400&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CBRS?period1=1778716800&period2=1779321600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CBRS?period1=1778716800&period2=1778803200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ALAB?period1=1710892800&period2=1711497600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/ALAB?period1=1710892800&period2=1710979200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/COIN?period1=1618358400&period2=1618963200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/COIN?period1=1618358400&period2=1618444800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/MDLN?period1=1765929600&period2=1766534400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/MDLN?period1=1765929600&period2=1766016000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GFS?period1=1635379200&period2=1635984000&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/GFS?period1=1635379200&period2=1635465600&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRDO?period1=1643241600&period2=1643846400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRDO?period1=1643241600&period2=1643328000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/VIK?period1=1714521600&period2=1715126400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/VIK?period1=1714521600&period2=1714608000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/RBLX?period1=1615334400&period2=1615939200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/RBLX?period1=1615334400&period2=1615420800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/KVUE?period1=1683158400&period2=1683763200&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/KVUE?period1=1683158400&period2=1683244800&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CPNG?period1=1615420800&period2=1616025600&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CPNG?period1=1615420800&period2=1615507200&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRCL?period1=1749081600&period2=1749686400&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/CRCL?period1=1749081600&period2=1749168000&interval=5m&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/RDDT?period1=1710979200&period2=1711584000&interval=1d&includePrePost=false&events=history
// Source: https://query1.finance.yahoo.com/v8/finance/chart/RDDT?period1=1710979200&period2=1711065600&interval=5m&includePrePost=false&events=history
window.firstDayBars = {
  "CBRS": [
    [
      "12:55",
      350.0,
      385.0,
      350.0,
      385.0,
      5012139
    ],
    [
      "13:00",
      385.0,
      385.0,
      385.0,
      385.0,
      5100
    ],
    [
      "13:05",
      370.0,
      379.81,
      325.0,
      369.99,
      5138291
    ],
    [
      "13:10",
      370.0,
      374.0,
      350.0,
      364.53,
      1656403
    ],
    [
      "13:15",
      363.28,
      365.26,
      335.99,
      343.19,
      1600763
    ],
    [
      "13:20",
      343.4399,
      344.54,
      325.98,
      326.825,
      1394412
    ],
    [
      "13:25",
      326.12,
      335.0,
      321.0,
      327.185,
      1490773
    ],
    [
      "13:30",
      326.94,
      337.5,
      324.0,
      330.77,
      787612
    ],
    [
      "13:35",
      330.13,
      343.0,
      330.13,
      335.0,
      668177
    ],
    [
      "13:40",
      335.0,
      336.5865,
      326.5,
      329.38,
      513347
    ],
    [
      "13:45",
      328.73,
      331.0,
      322.1601,
      325.81,
      698988
    ],
    [
      "13:50",
      325.815,
      328.0,
      307.0292,
      307.03,
      1230746
    ],
    [
      "13:55",
      307.01,
      312.0,
      302.3566,
      303.29,
      1014816
    ],
    [
      "14:00",
      303.275,
      306.69,
      300.0,
      301.18,
      1045681
    ],
    [
      "14:05",
      300.48,
      309.45,
      300.0,
      309.44,
      587168
    ],
    [
      "14:10",
      309.0,
      316.64,
      306.0,
      308.36,
      598160
    ],
    [
      "14:15",
      308.12,
      311.89,
      304.0,
      311.0,
      391264
    ],
    [
      "14:20",
      311.99,
      318.85,
      309.61,
      317.5,
      503847
    ],
    [
      "14:25",
      317.5,
      319.5,
      311.0,
      313.09,
      342706
    ],
    [
      "14:30",
      313.285,
      322.0,
      311.25,
      321.165,
      417115
    ],
    [
      "14:35",
      321.7623,
      324.0,
      317.21,
      322.15,
      383332
    ],
    [
      "14:40",
      322.02,
      325.0,
      318.75,
      324.845,
      388767
    ],
    [
      "14:45",
      325.0,
      327.7648,
      322.02,
      323.48,
      416374
    ],
    [
      "14:50",
      323.61,
      325.0,
      320.31,
      322.44,
      283998
    ],
    [
      "14:55",
      322.6025,
      326.9799,
      317.03,
      318.495,
      434998
    ],
    [
      "15:00",
      317.63,
      325.0,
      315.301,
      324.5,
      344076
    ],
    [
      "15:05",
      324.735,
      328.9,
      320.4,
      328.45,
      376150
    ],
    [
      "15:10",
      328.16,
      330.0,
      326.6,
      327.66,
      369154
    ],
    [
      "15:15",
      327.66,
      329.99,
      325.0,
      329.78,
      340890
    ],
    [
      "15:20",
      329.31,
      329.92,
      324.5,
      325.555,
      333080
    ],
    [
      "15:25",
      325.555,
      326.4999,
      320.0,
      320.4,
      344707
    ],
    [
      "15:30",
      320.03,
      321.28,
      312.32,
      318.735,
      517062
    ],
    [
      "15:35",
      318.98,
      322.0,
      316.51,
      319.73,
      345273
    ],
    [
      "15:40",
      319.55,
      321.73,
      315.52,
      316.25,
      346054
    ],
    [
      "15:45",
      316.26,
      319.25,
      311.0,
      311.0,
      442026
    ],
    [
      "15:50",
      311.0,
      317.98,
      305.16,
      317.5,
      552752
    ],
    [
      "15:55",
      317.25,
      317.5,
      309.1,
      310.3,
      747008
    ]
  ]
};
