// Generated by refresh_ipo_data.py on 2026-05-25.
// Source: https://stockanalysis.com/stocks/screener/
// Source: https://stockanalysis.com/ipos/2026/
// Source: https://stockanalysis.com/ipos/2025/
// Source: https://stockanalysis.com/ipos/2024/
// Source: https://stockanalysis.com/ipos/2023/
// Source: https://stockanalysis.com/ipos/2022/
// Source: https://stockanalysis.com/ipos/2021/
// Source: https://stockanalysis.com/stocks/googl/
// Source: https://stockanalysis.com/stocks/goog/
// Source: https://stockanalysis.com/stocks/tsla/
// Source: https://stockanalysis.com/stocks/amd/
// Source: https://stockanalysis.com/stocks/asml/
// Source: https://stockanalysis.com/stocks/jnj/
// Source: https://stockanalysis.com/stocks/cost/
// Source: https://stockanalysis.com/stocks/arm/
// Source: https://stockanalysis.com/stocks/baba/
// Source: https://stockanalysis.com/stocks/azn/
// Source: https://stockanalysis.com/stocks/panw/
// Source: https://stockanalysis.com/stocks/anet/
// Source: https://stockanalysis.com/stocks/adi/
// Source: https://stockanalysis.com/stocks/dell/
// Source: https://stockanalysis.com/stocks/san/
// Source: https://stockanalysis.com/stocks/mrvl/
// Source: https://stockanalysis.com/stocks/crwd/
// Source: https://stockanalysis.com/stocks/crm/
// Source: https://stockanalysis.com/stocks/uber/
// Source: https://stockanalysis.com/stocks/pdd/
// Source: https://stockanalysis.com/stocks/shop/
// Source: https://stockanalysis.com/stocks/sony/
// Source: https://stockanalysis.com/stocks/spot/
// Source: https://stockanalysis.com/stocks/now/
// Source: https://stockanalysis.com/stocks/cdns/
// Source: https://stockanalysis.com/stocks/hood/
// Source: https://stockanalysis.com/stocks/nu/
// Source: https://stockanalysis.com/stocks/crwv/
// Source: https://stockanalysis.com/stocks/cbrs/
// Source: https://stockanalysis.com/stocks/alab/
// Source: https://stockanalysis.com/stocks/coin/
// Source: https://stockanalysis.com/stocks/mdln/
// Source: https://stockanalysis.com/stocks/gfs/
// Source: https://stockanalysis.com/stocks/crdo/
// Source: https://stockanalysis.com/stocks/vik/
// Source: https://stockanalysis.com/stocks/rblx/
// Source: https://stockanalysis.com/stocks/vg/
// Source: https://stockanalysis.com/stocks/kvue/
// Source: https://stockanalysis.com/stocks/cpng/
// Source: https://stockanalysis.com/stocks/crcl/
// Source: https://stockanalysis.com/stocks/rddt/
// Source: https://stockanalysis.com/stocks/googl/company/
// Source: https://stockanalysis.com/stocks/goog/company/
// Source: https://stockanalysis.com/stocks/tsla/company/
// Source: https://stockanalysis.com/stocks/amd/company/
// Source: https://stockanalysis.com/stocks/asml/company/
// Source: https://stockanalysis.com/stocks/jnj/company/
// Source: https://stockanalysis.com/stocks/cost/company/
// Source: https://stockanalysis.com/stocks/arm/company/
// Source: https://stockanalysis.com/stocks/baba/company/
// Source: https://stockanalysis.com/stocks/azn/company/
// Source: https://stockanalysis.com/stocks/panw/company/
// Source: https://stockanalysis.com/stocks/anet/company/
// Source: https://stockanalysis.com/stocks/adi/company/
// Source: https://stockanalysis.com/stocks/dell/company/
// Source: https://stockanalysis.com/stocks/san/company/
// Source: https://stockanalysis.com/stocks/mrvl/company/
// Source: https://stockanalysis.com/stocks/crwd/company/
// Source: https://stockanalysis.com/stocks/crm/company/
// Source: https://stockanalysis.com/stocks/uber/company/
// Source: https://stockanalysis.com/stocks/pdd/company/
// Source: https://stockanalysis.com/stocks/shop/company/
// Source: https://stockanalysis.com/stocks/sony/company/
// Source: https://stockanalysis.com/stocks/spot/company/
// Source: https://stockanalysis.com/stocks/now/company/
// Source: https://stockanalysis.com/stocks/cdns/company/
// Source: https://stockanalysis.com/stocks/hood/company/
// Source: https://stockanalysis.com/stocks/nu/company/
// Source: https://stockanalysis.com/stocks/crwv/company/
// Source: https://stockanalysis.com/stocks/cbrs/company/
// Source: https://stockanalysis.com/stocks/alab/company/
// Source: https://stockanalysis.com/stocks/coin/company/
// Source: https://stockanalysis.com/stocks/mdln/company/
// Source: https://stockanalysis.com/stocks/gfs/company/
// Source: https://stockanalysis.com/stocks/crdo/company/
// Source: https://stockanalysis.com/stocks/vik/company/
// Source: https://stockanalysis.com/stocks/rblx/company/
// Source: https://stockanalysis.com/stocks/vg/company/
// Source: https://stockanalysis.com/stocks/kvue/company/
// Source: https://stockanalysis.com/stocks/cpng/company/
// Source: https://stockanalysis.com/stocks/crcl/company/
// Source: https://stockanalysis.com/stocks/rddt/company/
// Source: https://www.cerebras.ai/press-release/cerebras-systems-announces-pricing-of-initial-public-offering
window.ipos = [
  {
    "ticker": "GOOGL",
    "name": "Alphabet Inc.",
    "date": "2004-08-19",
    "exchange": "NASDAQ",
    "sector": "Internet Content & Information",
    "ipoPrice": null,
    "current": 382.97,
    "marketCap": 4640.0,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2004-08-19",
      "open": 2.5025,
      "high": 2.6041,
      "low": 2.4014,
      "close": 2.511,
      "volume": 893181924,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "GOOG",
    "name": "Alphabet Inc.",
    "date": "2004-08-19",
    "exchange": "NASDAQ",
    "sector": "Internet Content & Information",
    "ipoPrice": null,
    "current": 379.38,
    "marketCap": 4620.0,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2004-08-19",
      "open": 2.4907,
      "high": 2.5918,
      "low": 2.39,
      "close": 2.4991,
      "volume": 897427216,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "TSLA",
    "name": "Tesla, Inc.",
    "date": "2010-06-29",
    "exchange": "NASDAQ",
    "sector": "Auto Manufacturers",
    "ipoPrice": null,
    "current": 426.01,
    "marketCap": 1600.0,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2010-06-29",
      "open": 1.2667,
      "high": 1.6667,
      "low": 1.1693,
      "close": 1.5927,
      "volume": 281494500,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "AMD",
    "name": "Advanced Micro Devices, Inc.",
    "date": "1972-09-27",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": null,
    "current": 467.51,
    "marketCap": 762.32,
    "dealSize": null,
    "dayChange": null,
    "firstDay": null
  },
  {
    "ticker": "ASML",
    "name": "ASML Holding N.V.",
    "date": "1995-03-15",
    "exchange": "NASDAQ",
    "sector": "Semiconductor Equipment & Materials",
    "ipoPrice": null,
    "current": 1632.9,
    "marketCap": 641.16,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "1995-03-15",
      "open": 2.4351,
      "high": 2.7851,
      "low": 2.3742,
      "close": 2.7394,
      "volume": 71337728,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "JNJ",
    "name": "Johnson & Johnson",
    "date": "1944-09-24",
    "exchange": "NYSE",
    "sector": "Drug Manufacturers - General",
    "ipoPrice": null,
    "current": 234.34,
    "marketCap": 564.11,
    "dealSize": null,
    "dayChange": null,
    "firstDay": null
  },
  {
    "ticker": "COST",
    "name": "Costco Wholesale Corporation",
    "date": "1993-09-22",
    "exchange": "NASDAQ",
    "sector": "Discount Stores",
    "ipoPrice": null,
    "current": 1028.24,
    "marketCap": 456.18,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "1993-09-22",
      "open": 9.0,
      "high": 9.1562,
      "low": 8.9375,
      "close": 9.1562,
      "volume": 1186400,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "ARM",
    "name": "Arm Holdings plc",
    "date": "2023-09-14",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": 51.0,
    "current": 306.51,
    "marketCap": 326.13,
    "dealSize": null,
    "dayChange": 501.0,
    "firstDay": {
      "date": "2023-09-14",
      "open": 56.1,
      "high": 66.28,
      "low": 55.54,
      "close": 63.59,
      "volume": 130534500,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "BABA",
    "name": "Alibaba Group Holding Limited",
    "date": "2014-09-19",
    "exchange": "NYSE",
    "sector": "Internet Retail",
    "ipoPrice": null,
    "current": 130.0,
    "marketCap": 296.84,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2014-09-19",
      "open": 92.7,
      "high": 99.7,
      "low": 89.95,
      "close": 93.89,
      "volume": 271879400,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "AZN",
    "name": "AstraZeneca PLC",
    "date": "1993-05-12",
    "exchange": "NYSE",
    "sector": "Drug Manufacturers - General",
    "ipoPrice": null,
    "current": 187.03,
    "marketCap": 290.09,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "1993-05-12",
      "open": 10.5833,
      "high": 10.5833,
      "low": 10.0417,
      "close": 10.0833,
      "volume": 207000,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "PANW",
    "name": "Palo Alto Networks, Inc.",
    "date": "2012-07-20",
    "exchange": "NASDAQ",
    "sector": "Software - Infrastructure",
    "ipoPrice": null,
    "current": 260.58,
    "marketCap": 211.33,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2012-07-20",
      "open": 9.1917,
      "high": 10.345,
      "low": 8.85,
      "close": 8.855,
      "volume": 42096600,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "ANET",
    "name": "Arista Networks, Inc.",
    "date": "2014-06-06",
    "exchange": "NYSE",
    "sector": "Computer Hardware",
    "ipoPrice": null,
    "current": 154.03,
    "marketCap": 193.95,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2014-06-06",
      "open": 3.4531,
      "high": 3.75,
      "low": 3.4375,
      "close": 3.4375,
      "volume": 116081600,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "ADI",
    "name": "Analog Devices, Inc.",
    "date": "1972-04-03",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": null,
    "current": 397.07,
    "marketCap": 193.41,
    "dealSize": null,
    "dayChange": null,
    "firstDay": null
  },
  {
    "ticker": "DELL",
    "name": "Dell Technologies Inc.",
    "date": "1988-06-22",
    "exchange": "NYSE",
    "sector": "Computer Hardware",
    "ipoPrice": null,
    "current": 295.19,
    "marketCap": 191.75,
    "dealSize": null,
    "dayChange": null,
    "firstDay": null
  },
  {
    "ticker": "SAN",
    "name": "Banco Santander, S.A.",
    "date": "1987-07-29",
    "exchange": "NYSE",
    "sector": "Banks - Diversified",
    "ipoPrice": null,
    "current": 12.04,
    "marketCap": 182.02,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "1987-07-30",
      "open": 4.3199,
      "high": 4.3913,
      "low": 4.3199,
      "close": 4.3505,
      "volume": 5826240,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "MRVL",
    "name": "Marvell Technology, Inc.",
    "date": "2000-06-27",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": null,
    "current": 196.33,
    "marketCap": 171.68,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2000-06-30",
      "open": 13.8086,
      "high": 14.75,
      "low": 12.6875,
      "close": 14.25,
      "volume": 3518000,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CRWD",
    "name": "CrowdStrike Holdings, Inc.",
    "date": "2019-06-12",
    "exchange": "NASDAQ",
    "sector": "Software - Infrastructure",
    "ipoPrice": 34.0,
    "current": 663.46,
    "marketCap": 168.87,
    "dealSize": null,
    "dayChange": 1851.35,
    "firstDay": {
      "date": "2019-06-12",
      "open": 63.5,
      "high": 67.0,
      "low": 56.0,
      "close": 58.0,
      "volume": 19449200,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CRM",
    "name": "Salesforce, Inc.",
    "date": "2004-06-23",
    "exchange": "NYSE",
    "sector": "Software - Application",
    "ipoPrice": null,
    "current": 180.07,
    "marketCap": 147.31,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2004-06-23",
      "open": 3.75,
      "high": 4.325,
      "low": 3.6875,
      "close": 4.3,
      "volume": 43574400,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "UBER",
    "name": "Uber Technologies, Inc.",
    "date": "2019-05-10",
    "exchange": "NYSE",
    "sector": "Software - Application",
    "ipoPrice": 45.0,
    "current": 71.82,
    "marketCap": 146.2,
    "dealSize": null,
    "dayChange": 59.6,
    "firstDay": {
      "date": "2019-05-10",
      "open": 42.0,
      "high": 45.0,
      "low": 41.06,
      "close": 41.57,
      "volume": 186322500,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "PDD",
    "name": "PDD Holdings Inc.",
    "date": "2018-07-26",
    "exchange": "NASDAQ",
    "sector": "Internet Retail",
    "ipoPrice": null,
    "current": 94.52,
    "marketCap": 134.54,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2018-07-26",
      "open": 26.5,
      "high": 27.45,
      "low": 25.0,
      "close": 26.7,
      "volume": 43213200,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "SHOP",
    "name": "Shopify Inc.",
    "date": "2015-05-21",
    "exchange": "NASDAQ",
    "sector": "Software - Application",
    "ipoPrice": null,
    "current": 103.0,
    "marketCap": 134.0,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2015-05-21",
      "open": 2.8,
      "high": 2.874,
      "low": 2.411,
      "close": 2.568,
      "volume": 123039000,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "SONY",
    "name": "Sony Group Corporation",
    "date": "1958-12-01",
    "exchange": "NYSE",
    "sector": "Consumer Electronics",
    "ipoPrice": null,
    "current": 22.14,
    "marketCap": 133.59,
    "dealSize": null,
    "dayChange": null,
    "firstDay": null
  },
  {
    "ticker": "SPOT",
    "name": "Spotify Technology S.A.",
    "date": "2018-04-03",
    "exchange": "NYSE",
    "sector": "Internet Content & Information",
    "ipoPrice": null,
    "current": 519.86,
    "marketCap": 106.89,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2018-04-03",
      "open": 165.9,
      "high": 169.0,
      "low": 148.26,
      "close": 149.01,
      "volume": 30526500,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "NOW",
    "name": "ServiceNow, Inc.",
    "date": "2012-06-29",
    "exchange": "NYSE",
    "sector": "Software - Application",
    "ipoPrice": null,
    "current": 102.13,
    "marketCap": 105.33,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "2012-06-29",
      "open": 4.75,
      "high": 4.95,
      "low": 4.566,
      "close": 4.92,
      "volume": 54612000,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CDNS",
    "name": "Cadence Design Systems, Inc.",
    "date": "1987-06-10",
    "exchange": "NASDAQ",
    "sector": "Software - Application",
    "ipoPrice": null,
    "current": 373.59,
    "marketCap": 103.04,
    "dealSize": null,
    "dayChange": null,
    "firstDay": {
      "date": "1987-06-10",
      "open": 1.9444,
      "high": 2.1111,
      "low": 1.9444,
      "close": 2.0,
      "volume": 10395450,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "HOOD",
    "name": "Robinhood Markets, Inc.",
    "date": "2021-07-29",
    "exchange": "NASDAQ",
    "sector": "Capital Markets",
    "ipoPrice": 38.0,
    "current": 73.64,
    "marketCap": 66.31,
    "dealSize": null,
    "dayChange": 93.79,
    "firstDay": {
      "date": "2021-07-29",
      "open": 38.0,
      "high": 40.25,
      "low": 33.35,
      "close": 34.82,
      "volume": 102474700,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "NU",
    "name": "Nu Holdings Ltd.",
    "date": "2021-12-09",
    "exchange": "NYSE",
    "sector": "Banks - Regional",
    "ipoPrice": 9.0,
    "current": 12.73,
    "marketCap": 61.89,
    "dealSize": null,
    "dayChange": 41.44,
    "firstDay": {
      "date": "2021-12-09",
      "open": 11.25,
      "high": 12.24,
      "low": 10.01,
      "close": 10.33,
      "volume": 90160800,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CRWV",
    "name": "CoreWeave, Inc.",
    "date": "2025-03-28",
    "exchange": "NASDAQ",
    "sector": "Software - Infrastructure",
    "ipoPrice": 40.0,
    "current": 105.49,
    "marketCap": 57.55,
    "dealSize": null,
    "dayChange": 163.72,
    "firstDay": {
      "date": "2025-03-28",
      "open": 39.0,
      "high": 41.94,
      "low": 37.46,
      "close": 40.0,
      "volume": 41091100,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CBRS",
    "name": "Cerebras Systems Inc.",
    "date": "2026-05-14",
    "exchange": "NASDAQ",
    "sector": "Software - Infrastructure",
    "ipoPrice": 185.0,
    "current": 256.78,
    "marketCap": 55.24,
    "dealSize": 5550.0,
    "dayChange": 38.8,
    "firstDay": {
      "date": "2026-05-14",
      "open": 350.0,
      "high": 386.34,
      "low": 300.0,
      "close": 311.07,
      "volume": 33497900,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "ALAB",
    "name": "Astera Labs, Inc.",
    "date": "2024-03-20",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": 36.0,
    "current": 306.88,
    "marketCap": 52.6,
    "dealSize": null,
    "dayChange": 752.44,
    "firstDay": {
      "date": "2024-03-20",
      "open": 52.56,
      "high": 63.5,
      "low": 50.61,
      "close": 62.03,
      "volume": 16843300,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "COIN",
    "name": "Coinbase Global, Inc.",
    "date": "2021-04-14",
    "exchange": "NASDAQ",
    "sector": "Financial Data & Stock Exchanges",
    "ipoPrice": 250.0,
    "current": 184.99,
    "marketCap": 48.74,
    "dealSize": null,
    "dayChange": -26.0,
    "firstDay": {
      "date": "2021-04-14",
      "open": 381.0,
      "high": 429.54,
      "low": 310.0,
      "close": 328.28,
      "volume": 81065700,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "MDLN",
    "name": "Medline Inc.",
    "date": "2025-12-17",
    "exchange": "NASDAQ",
    "sector": "Medical Instruments & Supplies",
    "ipoPrice": 29.0,
    "current": 37.01,
    "marketCap": 48.62,
    "dealSize": null,
    "dayChange": 27.62,
    "firstDay": {
      "date": "2025-12-17",
      "open": 35.0,
      "high": 41.25,
      "low": 34.89,
      "close": 41.0,
      "volume": 78930900,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "GFS",
    "name": "GLOBALFOUNDRIES Inc.",
    "date": "2021-10-28",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": 47.0,
    "current": 85.64,
    "marketCap": 46.97,
    "dealSize": null,
    "dayChange": 82.21,
    "firstDay": {
      "date": "2021-10-28",
      "open": 47.01,
      "high": 48.0,
      "low": 44.48,
      "close": 46.4,
      "volume": 18618900,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CRDO",
    "name": "Credo Technology Group Holding Ltd",
    "date": "2022-01-27",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "ipoPrice": 10.0,
    "current": 218.41,
    "marketCap": 40.29,
    "dealSize": null,
    "dayChange": 2084.1,
    "firstDay": {
      "date": "2022-01-27",
      "open": 12.1,
      "high": 12.5,
      "low": 10.8,
      "close": 11.65,
      "volume": 5371700,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "VIK",
    "name": "Viking Holdings Ltd",
    "date": "2024-05-01",
    "exchange": "NYSE",
    "sector": "Travel Services",
    "ipoPrice": 24.0,
    "current": 84.23,
    "marketCap": 37.58,
    "dealSize": null,
    "dayChange": 250.96,
    "firstDay": {
      "date": "2024-05-01",
      "open": 26.15,
      "high": 26.86,
      "low": 25.71,
      "close": 26.1,
      "volume": 35017400,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "RBLX",
    "name": "Roblox Corporation",
    "date": "2021-03-10",
    "exchange": "NYSE",
    "sector": "Electronic Gaming & Multimedia",
    "ipoPrice": 45.0,
    "current": 48.16,
    "marketCap": 34.48,
    "dealSize": null,
    "dayChange": 7.02,
    "firstDay": {
      "date": "2021-03-10",
      "open": 64.5,
      "high": 74.83,
      "low": 60.5,
      "close": 69.5,
      "volume": 97069300,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "KVUE",
    "name": "Kenvue Inc.",
    "date": "2023-05-04",
    "exchange": "NYSE",
    "sector": "Household & Personal Products",
    "ipoPrice": 22.0,
    "current": 17.53,
    "marketCap": 33.66,
    "dealSize": null,
    "dayChange": -20.32,
    "firstDay": {
      "date": "2023-05-04",
      "open": 25.53,
      "high": 26.98,
      "low": 25.25,
      "close": 26.9,
      "volume": 77004200,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CPNG",
    "name": "Coupang, Inc.",
    "date": "2021-03-11",
    "exchange": "NYSE",
    "sector": "Internet Retail",
    "ipoPrice": 35.0,
    "current": 16.12,
    "marketCap": 28.94,
    "dealSize": null,
    "dayChange": -53.94,
    "firstDay": {
      "date": "2021-03-11",
      "open": 63.5,
      "high": 69.0,
      "low": 49.25,
      "close": 49.25,
      "volume": 91584100,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "CRCL",
    "name": "Circle Internet Group, Inc.",
    "date": "2025-06-05",
    "exchange": "NYSE",
    "sector": "Capital Markets",
    "ipoPrice": 31.0,
    "current": 113.12,
    "marketCap": 28.12,
    "dealSize": null,
    "dayChange": 264.9,
    "firstDay": {
      "date": "2025-06-05",
      "open": 69.0,
      "high": 103.75,
      "low": 64.0,
      "close": 83.23,
      "volume": 47192000,
      "source": "Yahoo 1d"
    }
  },
  {
    "ticker": "RDDT",
    "name": "Reddit, Inc.",
    "date": "2024-03-21",
    "exchange": "NYSE",
    "sector": "Internet Content & Information",
    "ipoPrice": 34.0,
    "current": 141.67,
    "marketCap": 27.27,
    "dealSize": null,
    "dayChange": 316.68,
    "firstDay": {
      "date": "2024-03-21",
      "open": 47.0,
      "high": 57.8,
      "low": 45.05,
      "close": 50.44,
      "volume": 48705500,
      "source": "Yahoo 1d"
    }
  }
];
